// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvckxsiniardtmlyaoeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2Y2t4c2luaWFyZHRtbHlhb2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNzE0OTUsImV4cCI6MjA3Mzg0NzQ5NX0.Z6rq_9AhpI61Iny8ZBdC2qat0afl3FVhnsnM7ac_ymw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});